In [5]:
import numpy as np

In [6]:
#Python Lists
arr1 = list(range(1000))
arr2 = list(range(1000,2000))

#Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [7]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result    

Wall time: 0 ns


832333500

In [8]:
%%time
np.dot(arr1_np, arr2_np)

Wall time: 0 ns


832333500

In [9]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134,58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [10]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [11]:
#2D array (matrix)
climate_data.shape

(5, 3)

In [12]:
weights = np.array([0.3, 0.2, 0.5])

In [13]:
weights

array([0.3, 0.2, 0.5])

In [14]:
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])

In [15]:
arr3 = np.array([[11, 12, 13, 14],
                 [15, 16, 17, 18],
                 [19, 11, 12, 13]])

In [18]:
#adding a scalar
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [22]:
#element-wise subtraction
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [23]:
#division by scalar
arr2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [24]:
arr2 // 2

array([[0, 1, 1, 2],
       [2, 3, 3, 4],
       [4, 0, 1, 1]], dtype=int32)

In [25]:
# element-wise application
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [26]:
# Modulus with scalar
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)